version: '3.5'
services:
  rpi-relay-controller:
    image: rpi-relay-controller
    container_name: rpi-relay-controller
    restart: unless-stopped
    privileged: true
    environment:
      NODE_ENV: production
      PORT: 8080
      DOOR_SEPARATOR: ____
      DEFAULT_LOCK_TIMEOUT: 3000
      AVAILABLE_RELAYS: config/available_relays.json
      TYPEORM_CONNECTION: sqlite
      TYPEORM_DATABASE: /usr/database/db.sqlite
      TYPEORM_ENTITIES: src/database/entities/*.js
      TYPEORM_MIGRATIONS: src/database/migrations/*.js
      TYPEORM_SUBSCRIBERS: src/database/subscribers/*.js
      TYPEORM_ENTITIES_DIR: src/database/entities
      TYPEORM_MIGRATIONS_DIR: src/database/migrations
      TYPEORM_SUBSCRIBERS_DIR: src/database/subscribers
      TYPEORM_LOGGING: false
    expose:
      - 8080
    volumes:
      - './database:/usr/database'
    networks:
      - network-bridge
    command: sh -c "npm run typeorm schema:sync && npm run typeorm migration:run && npm run runtime"

  nginx:
    image: nginx:mainline-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - './nginx:/etc/nginx/conf.d'
      - './page:/var/www/page'
    networks:
      - network-bridge

networks:
  network-bridge:
    driver: bridge
