version: '3.5'
services:
  rpi-relay-controller:
    image: rpi-relay-controller:latest
    container_name: rpi-relay-controller
    restart: unless-stopped
    privileged: true
    environment:
      NODE_ENV: production
      PORT: 8080
      DOOR_SEPARATOR: ____
      DEFAULT_LOCK_TIMEOUT: 3000
      AVAILABLE_RELAYS: /usr/config/available_relays.json
    expose:
      - 8080
    volumes:
      - './database:/usr/database'
      - './config:/usr/config'
    networks:
      - network-bridge
    command: sh -c "npm run typeorm schema:sync && npm run typeorm migration:run && npm run runtime"

  nginx:
    image: nginx:mainline-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - './nginx:/etc/nginx/conf.d'
      - './page:/var/www/page'
    networks:
      - network-bridge

networks:
  network-bridge:
    driver: bridge
